// import './js/type.js'
// import './js/consoleMethod.js'
// import './js/function.js'
// import './js/trycatch.js'
// import './js/switchelse.js'
// import './js/scopeChain.js'
// import './js/closure.js'
import './js/currying.js'
