// import './js/type.js'
// import './js/consoleMethod.js'
// import './js/function.js'
// import './js/trycatch.js'
// import './js/switchelse.js'
// import './js/scopeChain.js'
// import './js/closure.js'
// import './js/currying.js'
// import './js/hoisting.js'
// import './js/useStrict.js'
// import './js/handleNumber.js'
// import './js/codingStyle.js'
// import './js/objectOriented.js'
import './js/prototype.js'
// import './js/this.js'
